### ISSUE TITLE
adding a field with the omitted fields

### ISSUE THREAD

**Issue by guydou** [dbrgn/drf-dynamic-fields#26]
hi 
It could be awesome If I could get a new field on the serialzier listing all the fields that were omitted.

The usecase of that, is when my client gets a  response he stores the response is a cache, 

When he uses the cache he needs to know if the object didn't have the field or if it is omitted,
if it is omitted they will  try to get the omitted fields from my service 

WDYT?

Thanks, Guy

**Comment by dbrgn** [comment]
That sounds like a good case for a project-specific custom serializer to me :slightly_smiling_face: You can use the [very simple code of this library](https://github.com/dbrgn/drf-dynamic-fields/blob/master/drf_dynamic_fields/__init__.py) as a basis.

I don't think it makes sense to put this feature in the library, since it's probably a very rare use case.

**Comment by jtrain** [comment]
Its a nice idea for your API customers, and lucky as @dbrgn says, you can customize this yourself.

You'd just need to remember what the original set of fields where, and the current set of fields once the serializer is initialized. The difference between the two is what you've asked for. You could probably do it in a `serializers.SerializerMethodField`. Or if this was a common part of your API in a custom field you attach to each of your serializers.

**Comment by guydou** [comment]
thanks guyd
